
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: PhoneModule
        uri: http://localhost:8082
        predicates:
        - Path=/phones/**
        - Path=/brands/**
      - id: CartModule
        uri: http://localhost:8083
        predicates:
        - Path=/carts/**
        - Path=/cartItems/**
      - id: BrandModule
        uri: http://localhost:8084
        predicates:
        - Path=/user/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/phoneup_db?createDatabaseIfNotExist=true&&allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
    show-sql: true
jwt:
  secret: nmthuan0712

  
